FROM oraclelinux:8.9

# OpenJDK 17 설치
RUN yum install -y tar gzip wget && \
    wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-aarch64_bin.tar.gz && \
    tar -zxvf openjdk-17.0.2_linux-aarch64_bin.tar.gz -C /opt && \
    rm openjdk-17.0.2_linux-aarch64_bin.tar.gz

# 환경 변수 설정
ENV JAVA_HOME=/opt/jdk-17.0.2
ENV PATH=$PATH:$JAVA_HOME/bin
ENV TZ=Asia/Seoul
ENV active_profile=prod

# 시간대 설정
RUN dnf install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# 크롬 관련 패키지 설치
RUN wget https://kojipkgs.fedoraproject.org//packages/zlib/1.2.13/5.eln134/aarch64/zlib-1.2.13-5.eln134.aarch64.rpm && \
    wget https://kojipkgs.fedoraproject.org//packages/zlib/1.2.13/5.eln134/aarch64/minizip-compat-1.2.13-5.eln134.aarch64.rpm && \
    wget https://kojipkgs.fedoraproject.org//packages/nss-mdns/0.14.1/9.el8/aarch64/nss-mdns-0.14.1-9.el8.aarch64.rpm && \
    wget https://kojipkgs.fedoraproject.org//packages/chromium/120.0.6099.224/1.el8/aarch64/chromium-common-120.0.6099.224-1.el8.aarch64.rpm && \
    wget https://kojipkgs.fedoraproject.org//packages/chromium/120.0.6099.224/1.el8/aarch64/chromedriver-120.0.6099.224-1.el8.aarch64.rpm && \
    wget https://kojipkgs.fedoraproject.org//packages/chromium/120.0.6099.224/1.el8/aarch64/chromium-120.0.6099.224-1.el8.aarch64.rpm && \
    dnf localinstall zlib-1.2.13-5.eln134.aarch64.rpm && \
    dnf localinstall minizip-compat-1.2.13-5.eln134.aarch64.rpm && \
    dnf localinstall nss-mdns-0.14.1-9.el8.aarch64.rpm && \
    dnf localinstall chromium-common-120.0.6099.224-1.el8.aarch64.rpm && \
    dnf localinstall chromedriver-120.0.6099.224-1.el8.aarch64.rpm && \
    dnf localinstall chromium-120.0.6099.224-1.el8.aarch64.rpm

# nslookup, telnet 설치
RUN dnf install -y bind-utils telnet
