spring:
  application:
    name: ${APPLICATION_NAME}

  datasource:
    app:
      url: ${APP_DATABASE_URL}
      username: ${APP_DATABASE_USER}
      password: ${APP_DATABASE_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver
      configuration:
        maximum-pool-size: ${APP_DATABASE_MAXIMUM_POOL_SIZE}

    batch:
      url: ${BATCH_DATABASE_URL}
      username: ${BATCH_DATABASE_USER}
      password: ${BATCH_DATABASE_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver
      configuration:
        maximum-pool-size: ${BATCH_DATABASE_MAXIMUM_POOL_SIZE}

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    elasticsearch:
      repositories:
        enabled: false

elasticsearch:
  config:
    host-and-port: ${ELASTICSEARCH_URL}
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PASSWORD}

server:
  port: ${APPLICATION_PORT}