spring:
  application:
    name: ${APPLICATION_NAME}

  datasource:
    url: ${APP_DATABASE_URL}
    username: ${APP_DATABASE_USER}
    password: ${APP_DATABASE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: ${APP_DATABASE_MAXIMUM_POOL_SIZE}

  jpa:
    hibernate:
      ddl-auto: none
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false

  redis-pub-sub:
    channel: ${REDIS_PUB_SUB_CHANNEL}

management:
  server:
    port: ${ACTUATOR_EXPOSURE_PORT}
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSURE_INCLUDE}
        exclude: ${ACTUATOR_EXPOSURE_EXCLUDE}

elasticsearch:
  config:
    host-and-port: ${ELASTICSEARCH_URL}
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PASSWORD}

server:
  port: ${APPLICATION_PORT}

application:
  allow-origins: ${ALLOW_ORIGINS}

cookie:
  secure: true
  domain: ${COOKIE_DOMAIN}

decorator:
  datasource:
    p6spy:
      enable-logging: false