spring:
  application:
    name: "LIVE_FEED_SAVER"

  kafka:
    bootstrap-servers: localhost:9093
    listener:
      type: batch
      concurrency: 3
      ack-mode: batch
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

opensearch:
  uris: https://localhost:9200
  username: admin
  password: admin
