name: Actions Runner Controller
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'LF-57/cd-arc'

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Extract version variable
        run: |
          echo "BATCH_APP_VERSION=$(./gradlew :LiveFeedBatch:properties -q | grep version | awk -F ' ' '{ print $2 }')" >> $GITHUB_ENV
          echo "SERVICE_APP_VERSION=$(./gradlew :LiveFeedService:properties -q | grep version | awk -F ' ' '{ print $2 }')" >> $GITHUB_ENV

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Rolling update
        run: |
          kubectl set image cronjob/batch-cron-job batch-container=ghcr.io/live-feed/live-feed-batch:${{ env.BATCH_APP_VERSION }} -n application
          kubectl set image deployment/service-app service-app=ghcr.io/live-feed/live-feed-service:${{ env.SERVICE_APP_VERSION }} -n application
